id: AF14A5D45
title: 'The Concentration of Blessings: Red Tārā Lineage Prayer'
type: translation
pechas:
- IAC1E2CA9
- ID8B7DE90
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:06.089660
  last_modified_at: 2023-01-04 12:15:06.089670
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IAC1E2CA9/D1E3: 1ABE
  ID8B7DE90/F931: 1ABE
